kmi_system_information_overview:
  path: /admin/system
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:index}
  methods:  [GET]

kmi_system_information_log_view:
  path: /admin/system/log/{id}
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:logView}
  methods:  [GET]
  requirements:
    id: \d+

kmi_system_information_info:
  path: /admin/system/info
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:info}
  methods:  [GET]