kmi_system_information_overview:
  path: /admin/system
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:index}
  methods:  [GET]

kmi_system_information_log_view:
  path: /admin/system/log/{id}
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:logView}
  methods:  [GET]

kmi_system_information_info:
  path: /admin/system/info
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:info}
  methods:  [GET]

kmi_system_information_phpinfo:
  path: /admin/system/phpinfo
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:phpInfo}
  methods:  [GET]

kmi_system_information_clearcache:
  path: /admin/system/clearcache
  defaults: {_controller: Kmi\SystemInformationBundle\Controller\Admin\SystemController:clearCache}
  methods:  [GET]