services:
  Kmi\SystemBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Admin}'

  Kmi\SystemBundle\Controller\Admin\SystemController:
    class: Kmi\SystemBundle\Controller\Admin\SystemController
    tags: ['controller.service_arguments']
    public: true
