services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kmi\SystemInformationBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Admin}'

  Kmi\SystemInformationBundle\Controller\Admin\SystemController:
    class: Kmi\SystemInformationBundle\Controller\Admin\SystemController
    tags: ['controller.service_arguments']
    public: true

  Kmi\SystemInformationBundle\Twig\FormatBytesExtension:
    class: Kmi\SystemInformationBundle\Twig\FormatBytesExtension
    tags:
      - { name: twig.extension }