services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kmi\SystemInformationBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Admin}'

  Kmi\SystemInformationBundle\Controller\Admin\SystemController:
    class: Kmi\SystemInformationBundle\Controller\Admin\SystemController
    tags: ['controller.service_arguments']
    public: true

  Kmi\SystemInformationBundle\Service\CheckService:
    class: Kmi\SystemInformationBundle\Service\CheckService
    arguments:
      - '@liip_monitor.helper.runner_manager'

  Kmi\SystemInformationBundle\Service\LogService:
    class: Kmi\SystemInformationBundle\Service\LogService
    arguments:
      - '@service_container'

  Kmi\SystemInformationBundle\Service\InformationService:
    class: Kmi\SystemInformationBundle\Service\InformationService
    arguments:
      - '@service_container'


  Kmi\SystemInformationBundle\Service\DependencyService:
    class: Kmi\SystemInformationBundle\Service\DependencyService
    arguments:
      - '@service_container'

  Kmi\SystemInformationBundle\Service\MailService:
    class: Kmi\SystemInformationBundle\Service\MailService
    arguments:
      - '@service_container'

  Kmi\SystemInformationBundle\Service\DatabaseService:
    class: Kmi\SystemInformationBundle\Service\DatabaseService
    arguments:
      - '@service_container'

  Kmi\SystemInformationBundle\Twig\SystemExtension:
    class: Kmi\SystemInformationBundle\Twig\SystemExtension
    tags:
      - { name: twig.extension }

  Kmi\SystemInformationBundle\Twig\VersionExtension:
    class: Kmi\SystemInformationBundle\Twig\VersionExtension
    tags:
      - { name: twig.extension }

  Kmi\SystemInformationBundle\Twig\EnvironmentExtension:
    class: Kmi\SystemInformationBundle\Twig\EnvironmentExtension
    tags:
      - { name: twig.extension }

  Kmi\SystemInformationBundle\Twig\SystemIndicatorExtension:
    class: Kmi\SystemInformationBundle\Twig\SystemIndicatorExtension
    tags:
      - { name: twig.extension }

  kmi_system_information_bundle.configuration_loader:
    class: Kmi\SystemInformationBundle\Service\ConfigurationLoader
    arguments:
      - ~