services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kmi\SystemInformationBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Admin}'

  Kmi\SystemInformationBundle\Controller\Admin\SystemController:
    class: Kmi\SystemInformationBundle\Controller\Admin\SystemController
    tags: ['controller.service_arguments']
    public: true

  Kmi\SystemInformationBundle\Service\CheckService:
    class: Kmi\SystemInformationBundle\Service\CheckService
    arguments:
      - '@service_container'

  Kmi\SystemInformationBundle\Service\LogService:
    class: Kmi\SystemInformationBundle\Service\LogService

  Kmi\SystemInformationBundle\Service\InformationService:
    class: Kmi\SystemInformationBundle\Service\InformationService
    arguments:
      - '@service_container'

  Kmi\SystemInformationBundle\Twig\SystemExtension:
    class: Kmi\SystemInformationBundle\Twig\SystemExtension
    tags:
      - { name: twig.extension }